#if !canImport(ObjectiveC)
import XCTest

extension XCTestExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestExtensionsTests = [
        ("testFlags", testFlags),
        ("testProductsDirectory", testProductsDirectory),
        ("testResources", testResources),
        ("testResults", testResults),
        ("testTemporaryFile", testTemporaryFile),
        ("testTestBundle", testTestBundle),
        ("testTestBundleName", testTestBundleName),
    ]
}

extension XCTestRunnerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestRunnerTests = [
        ("testRunner", testRunner),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XCTestExtensionsTests.__allTests__XCTestExtensionsTests),
        testCase(XCTestRunnerTests.__allTests__XCTestRunnerTests),
    ]
}
#endif
