#if !canImport(ObjectiveC)
import XCTest

extension XCTestExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestExtensionsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XCTestExtensionsTests.__allTests__XCTestExtensionsTests),
    ]
}
#endif
